# Generated by Django 5.2 on 2025-05-31 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField()),
                ('brand', models.CharField()),
                ('model', models.CharField()),
                ('type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_image', models.ImageField(upload_to='')),
                ('destination_longitude', models.CharField()),
                ('destination_lattitude', models.CharField()),
                ('origin_longitude', models.CharField()),
                ('origin_lattitude', models.CharField()),
                ('route_cost', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Current_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField()),
                ('latitude', models.CharField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.vehicle')),
            ],
        ),
    ]
