# Generated by Django 5.2 on 2025-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_route_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='consumption_per_km',
            field=models.IntegerField(default=1),
        ),
    ]
